[package]
name = "anstml"
version = "0.1.0"
edition = "2021"

[lib]
name = "anstml"
src = "src/lib.rs"

[[bin]]
name = "anstml"
src = "src/anstml.rs"

[dependencies]
ansi_colours = "1.2.3"
html = "0.6.3"
itertools = "0.13.0"

[dev-dependencies]
rstest = "*"
