name: "build nix"
on:
  pull_request:
  push:
jobs:
  check_anstml_package:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: nix flake check -L --all-systems
  build_anstml_package:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: nix build -L
  build_anstml_shell:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: nix shell -L --command echo 'it works'
